### ISSUE TITLE
Mac binaries

### ISSUE THREAD

**Issue by Romvnly-Gaming** [SecretX33/ZipSource#1]
Mac prebuilt binaries when

**Comment by SecretX33** [comment]
Good afternoon! Your request is currently being worked on. 😄 

To build MacOS binaries, I have to set up GitHub Actions on this repository so I can automate the creation of the binaries for all three major OSes (up to this point I was manually building the releases, but since I do not own a Mac I am not able to build it for Mac). 

I attempted to create an Action for this yesterday, but seems like I found an issue in the release step action that prevents it from finding any built binaries. I've opened an [**Issue**](https://github.com/softprops/action-gh-release/issues/324) in the official repository, so we have to wait for them to explain to me what is happening. After this issue is fixed, I'll be copying the newly created Action pipeline to this repository and rebuilding the latest release to include the MacOS binary.

[This](https://github.com/SecretX33/test-rust-workflow) is the repository I'm using to create and test the build automation if you are curious.

**Comment by SecretX33** [comment]
The issue I mentioned in the previous comment was solved, hurray! If you have a MacOS, could you please this test this binary and let me know if it works?

[ZipSource.x64.MacOS.zip](https://github.com/SecretX33/ZipSource/files/10716293/ZipSource.x64.MacOS.zip)

**Comment by Romvnly-Gaming** [comment]
I'll go and get my MacBook soon

**Comment by Romvnly-Gaming** [comment]
Works on my machine

**Comment by SecretX33** [comment]
Glad to hear that! Since everything worked out just, I've opened a PR creating a new deployment pipeline that will build a binary for all these OSes:

- Windows x32
- Windows x64
- Linux x64
- MacOS x64

I also atempted to have it build for MacOS and Linux ARM based systems too, but since I am no expert in Rust in general I wasn't able to make the build for ARM work while in an x64 system (which is what GitHub Actions use). If someone opens a new issue asking for this I might consider investing more time into that, but for now, I think that what was done is enough.

Thanks for opening an Issue and helping improve the project!
